### ISSUE TITLE
Removing widgets results in unstable behavior

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#17]
Using the following code:
```crystal
require "gtk4"

app = Gtk::Application.new("com.example.issue", Gio::ApplicationFlags::None)
app.activate_signal.connect do
  window = Gtk::ApplicationWindow.new(app)
  box = Gtk::Box.new
  window.child = box

  label = Gtk::Label.new(label: "Test!")
  box.append(label)
  box.remove(label)

  window.present

  GLib.timeout_seconds(5) do
    GC.collect
    false
  end
end
app.run(ARGV)
```

Results in the following output (using `-Ddebugmemory`):
```
~Gtk::ApplicationWindow at 0x18f0350 - ref count: 2
~Gtk::Box at 0x183f180 - ref count: 1

(crystal-run-test2.tmp:54281): Gtk-CRITICAL **: 22:26:25.976: GtkBox 0x183f180 has a parent GtkApplicationWindow 0x18f0350 during dispose. Parents hold a reference, so this should not happen.
Did you call g_object_unref() instead of gtk_widget_unparent()?
~Gtk::Label at 0x18c6180 - ref count: 0

(crystal-run-test2.tmp:54281): GLib-GObject-CRITICAL **: 22:26:25.976: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(crystal-run-test2.tmp:54281): Gtk-CRITICAL **: 22:26:28.854: gtk_accessible_get_accessible_role: assertion 'GTK_IS_ACCESSIBLE (self)' failed

[continues like this]
```

..while making the program unstable (ex. header bar disappears or buttons in gtk inspector move to random places):
![Bildschirmfoto vom 2022-04-13 22-37-42](https://user-images.githubusercontent.com/14961554/163266259-8f9644e5-09ca-4bf1-bcdf-9d8f54a46633.png)

**Comment by hugopl** [comment]
I think this is related to floating references, the generator need to call `g_object_sink_ref` in the constructor of objects that inherit `InitiallyUnowned` and it isn’t.

If so, the fix for this should also fix https://github.com/hugopl/gtk4.cr/issues/3

**Comment by hugopl** [comment]
This patch on gi-crystal fixes https://github.com/hugopl/gtk4.cr/issues/3 and this issue
```Diff
diff --git a/ecr/gobject_constructor.ecr b/ecr/gobject_constructor.ecr
index b3c631c..dc9732e 100644
--- a/ecr/gobject_constructor.ecr
+++ b/ecr/gobject_constructor.ecr
@@ -12,4 +12,5 @@ def initialize(<%= gobject_constructor_parameter_declaration %>)
   <% end %>
 
   @pointer = LibGObject.g_object_new_with_properties(<%= to_crystal_type(object, false) %>.g_type, _n, _names, _values)
-end
\ No newline at end of file
+  LibGObject.g_object_ref_sink(self) if LibGObject.g_object_is_floating(self) == 1
+end
```

But I'll write a test on gi-crystal for this before land this fix on gi-crystal.

**Comment by hugopl** [comment]
Fix landed :tada: 

I was waiting to finish the fix for https://github.com/hugopl/gtk4.cr/issues/12 to do another release, but I think this fix on floating references is a critical fix and deserve to be released ASAP.

Thanks very much for reporting!
