### ISSUE TITLE
Gtk::Snapshot#append_border does not compile

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#19]
The following code does not compile:
```crystal
require "gtk4"

snapshot = Gtk::Snapshot.new

size = Graphene::Size.new(148, 405)

rect = Graphene::Rect.new(
  origin: Graphene::Point.new(0.0_f32, 0.0_f32),
  size: size
)

rounded_rect = Gsk::RoundedRect.new.init_from_rect(
  bounds: rect,
  radius: 90.0
)

snapshot.append_border(rounded_rect, [10f32, 10f32, 10f32, 10f32], [Gdk::RGBA.new(1.0, 0.0, 0.0, 1.0), Gdk::RGBA.new(1.0, 0.0, 0.0, 1.0), Gdk::RGBA.new(1.0, 0.0, 0.0, 1.0), Gdk::RGBA.new(1.0, 0.0, 0.0, 1.0)])
```

With the following error message:
```
In lib/gtk4/lib/gi-crystal/src/auto/gtk-4.0/snapshot.cr:58:56

 58 | LibGtk.gtk_snapshot_append_border(self, outline, border_width, border_color)
                                                       ^-----------
Error: argument 'border_width' of 'LibGtk#gtk_snapshot_append_border' must be Pointer(StaticArray(Float32, 4)), not Pointer(Float32)

```

**Comment by hugopl** [comment]
The lib declaration seems wrong:
```Crystal
fun gtk_snapshot_append_border(
  this : Void*,
  outline : Pointer(Void),
  border_width : Pointer(Float32[4]),
  border_color : Pointer(Void[4])
) : Void
```
where in C this is:
```
void
gtk_snapshot_append_border (
  GtkSnapshot* snapshot,
  const GskRoundedRect* outline,
  const float* border_width,
  const GdkRGBA* border_color
)
```

There is an annotation `(array fixed-size=4)` on these bad fields, I think the lib code must ignore this annotation and just the generated Crystal code must deal with it.

Fixable, but will wait a bit while I finish other things, my current todo list (in no particular order) is:

- Be able to use XML widget templates (this is why I landed some basic stuff for GObject sublassing in last gi-crystal).
- Generate write code for callback parameters (this is almost done).
- Write a `HACKING.md` explaining who the generator works.

**Comment by hugopl** [comment]
Fixed :-)

Current code that deal with array parameters need some love, currently don't matter if you send a tuple or an array the generated code will transform it to an Array and get the memory address... i.e. send tuples is in fact less efficient than using arrays :disappointed: , but this will change in the future, so better keep the current code sending tuples.

The idea in the future is to have a version of the method that receives tuples and other that receives a `Enumerable`, but later... there's a lot of basic stuff not working yet to be fixed before start thinking about optimizations.
