### ISSUE TITLE
[Feature Request] libadwaita bindings

### ISSUE THREAD

**Issue by GeopJr** [hugopl/gtk4.cr#2]
I'm not sure if this is outside the scope of this repo but would be nice to have!
I don't know if gi-crystal is able to generate bindings for it (I couldn't manage to create them from a quick try).

Additional context:
I have to migrate [Hashbrown](https://github.com/GeopJr/Hashbrown/) to GTK 4 and need to follow GNOME HIG. Currently, with [crystal-gobject](https://github.com/jhass/crystal-gobject) I'm able to use libhandy widgets (through Glade ui files at least), but using gtk4.cr I get the following (**expected**) error:

<details><summary>(Test ui file with an `AdwAvatar` widget)</summary>
<p>

```bash
Gtk-ERROR **: 11:52:58.647: failed to add UI from file /home/geopjr/projects/gtk4.cr/examples/adw_test.ui: /home/geopjr/projects/gtk4.cr/examples/adw_test.ui:12:1 Invalid object type 'AdwAvatar'
```

</p>
</details>

**Comment by hugopl** [comment]
This error comes from GTK, nto the binding, UI files format changed on GTK4, you need to convert then using:

`gtk4-builder-tool simplify --3to4 MY_UI_FILE --replace`

I need to pause and write some documentation for gi-crystal, however I'm waiting the code/API to stabilize a bit before putting some effort on documentation, currently I'm doing a refactor on gi-crystal to cleanup some code in the generator that become messy faster than I thought.

Anyway, I think `libadwaita` probably will deserve its own shard, this one is already with GTK4 and all its dependencies (GDK, GSK, etc).

**Comment by GeopJr** [comment]
I suspect there's something wrong with my `libadwaita` install since a ui file as simple as this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <requires lib="gtk" version="4.0"/>
  <requires lib="libadwaita" version="1.0"/>
  <object class="GtkWindow">
    <property name="title">Hello World</property>
    <child type="titlebar">
      <object class="GtkHeaderBar"/>
    </child>
    <child>
      <object class="AdwAvatar"/>
    </child>
  </object>
</interface>
```

causes the same error as before (`Invalid object type 'AdwAvatar'`).
Thanks for info however! :)
Closing.
