### ISSUE TITLE
Update docs at https://hugopl.github.io/gtk4.cr/

### ISSUE THREAD

**Issue by megatux** [hugopl/gtk4.cr#23]
I'm seeing awesome progress on this shard <3. I would like to continue my Crystal & GUI app-dev journey and I was thinking if you could update the docs in your site. I see 0.5.0v and looks like it's on 0.7.0 now. Thanks!

**Comment by hugopl** [comment]
Oops, I forgot to do it.

Ideally would be nice to have a github actions to do this task automatically, i.e.

```
git checkout gh-pages
git merge master
make doc
git add doc
git push origin gh-pages
```

But deal of github actions is boring, hehe, so I prefer do fun stuff like work on the shard itself. However I would appreciate if someone create a PR adding a github action to run the tests and/or generate the docs every time a new tag is created.
