### ISSUE TITLE
Add more options to `register_resource`

### ISSUE THREAD

**Issue by GeopJr** [hugopl/gtk4.cr#29]
On Collision I use the `--sourcedir` flag while compiling resources with `glib-compile-resources`. Should `register_resource` accept an extra parameter for it or maybe just an extra parameter for extra flags?

eg.
```crystal
  macro register_resource(resource_file, flags)
    {%
      `glib-compile-resources #{flags} --target crystal-gio-resource.gresource #{resource_file}`
...

register_resource("./data.gresource.xml", "--sourcedir data")
```

**Comment by hugopl** [comment]
source dir is default to project dir, but would be nice to have an extra option for data, but I prefer the syntax:

```Crystal
register_resource("./data.gresource.xml", sourcedir: "data")
```
