### ISSUE TITLE
Git repo size very big (gh_pages branch?)

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#37]
When trying to clone this git repo, I see the following on the terminal:
```
⬢[blobcodes@toolbox ~]$ time git clone https://github.com/hugopl/gtk4.cr.git
Cloning into 'gtk4.cr'...
remote: Enumerating objects: 46671, done.
remote: Counting objects: 100% (4742/4742), done.
remote: Compressing objects: 100% (369/369), done.
remote: Total 46671 (delta 4297), reused 4741 (delta 4297), pack-reused 41929
Receiving objects: 100% (46671/46671), 89.76 MiB | 9.54 MiB/s, done.
Resolving deltas: 100% (42290/42290), done.

real	0m18.722s
user	0m51.873s
sys	0m1.766s
```

The repo is just under 90 MB big, which will be downloaded everytime I use `shards update`. As you can see, this takes over 18 seconds, which is a lot for such a simple shard. Also I don't have the worst internet connection, others will probably need even more time.

I think this is because when cloning the repo, you download every version of the docs in the `gh-pages` branch. That is not really necessary and I would recommend either using GitLab CI so the docs do not need to be uploaded to the repo or to automatically purge the `gh-pages` branch.

**Comment by hugopl** [comment]
I agree 100%, a forced push to gh-pages could fix this on client side. The current solution doesn't scale.

Long time I don't check github pages docs, so I don't known if it's possible or how it's done to have the github pages not in the git repository.
