### ISSUE TITLE
Shards install error

### ISSUE THREAD

**Issue by BigBoyBarney** [hugopl/gtk4.cr#68]
Hi!

I'm completely new to Crystal, so this might be (or probably, rather) an issue on my end. However, when I try installing gtk4.cr in my project, I get the error in the screenshot:
![image](https://github.com/hugopl/gtk4.cr/assets/86712892/56c0b36f-0bf6-4fbd-bd53-499c1d55245f)

Steps:
1. `shards init`
2. Add gtk4.cr as dependency. `shard.yml` looks like this:
```yaml
name: 
version: 0.1.0

dependencies:
  gtk4:
    github: hugopl/gtk4.cr
```
3. `shards install`
4. The error mentioned above happens

Thanks in advance!
Cheers!

-----

Also completely unrelated, but I thought I'd ask since you seem like a Crystal expert :D What's your IDE of choice for Crystal development? I couldn't get nvim to syntax highlight, so VScodium with the Crystal-lang extension seems to be the only option. I saw you were working on your own IDE as well, but that's still relatively early in development.

Thanks again!!

**Comment by BigBoyBarney** [comment]
# EDIT
![image](https://github.com/hugopl/gtk4.cr/assets/86712892/c7538dba-11df-4ca6-b5d4-ad4ca09f4200)
The error seemed to be cause by the fact that I had a whitespace in the directory path.

**Comment by hugopl** [comment]
yeah, it must not error on directories with whitespace, this is very good first issue to fix and the print you sent tells exactly where the error is. But the fix must be done in gi-crystal shard, not on gtk4 shard.

I'm with two newborns at home so I'll be busy for some months, but I guess I can still find some time to at least review and merge simple patches sent by you or someone else.

**Comment by BigBoyBarney** [comment]
Enjoy your time at home, and thank you for these bindings!
Didn't think that a relatively unknown language like Crystal would have such extensive GTK4 compatibility.  Amazing stuff!

**Comment by BigBoyBarney** [comment]
Even after PR was merged, I'm running into the same issue, on a completely new project.
![image](https://github.com/hugopl/gtk4.cr/assets/86712892/f768ad7d-2359-4aea-be28-630107cd2a45)

The error still shows the old code. Do you have an idea why this could be?

Thanks!

**Comment by hugopl** [comment]
It's because no releases were made yet, you can force the version of gi-crystal shard using a shards.override.yml file.

https://crystal-lang.org/reference/1.12/man/shards/index.html#fixing-dependency-version-conflicts

**Comment by BigBoyBarney** [comment]
That worked like a charm. Thanks a lot and sorry for the trouble!

Cheers!
