### ISSUE TITLE
Cannot initialize Graphene::Rect

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#9]
The following code:
```crystal
require "gtk4"

Graphene::Rect.new(
  origin: Graphene::Point.zero,
  size: Graphene::Size.zero
)
```

Results in the following compile-time exception:
```
In lib/gtk4/src/graphene-1.0/rect.cr:45:61

 45 | _var = (@pointer + 0).as(Pointer(LibGraphene::Point)).value = value.to_unsafe
                                                            ^----
Error: no overload matches 'Pointer(LibGraphene::Point)#value=' with type Pointer(Void)

Overloads are:
 - Pointer(T)#value=(value : T)
```

**Comment by hugopl** [comment]
The problem was with structs that had struct as members... 

This:
`(@pointer + 0).as(Pointer(LibGraphene::Point)).value = value.to_unsafe`
needed to be:
`(@pointer + 0).as(Pointer(Void)).value = value.to_unsafe`

besides the getter that was using a transfer full, causing a double free.

**Comment by hugopl** [comment]
I had forgotten to update `shard.yml` from this shard to use newer gi-crystal that have the fix, now it's updated, so `Graphene::Rect` can be used :-)
